spring:
  jmx:
    enabled: false
  main:
    web-application-type: none

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

rabbitmq:
  exchange.name: smpp.topic
  mo:
    queue.name: smpp.inbound
    routing.key: smpp_direct_to_inbound
  mt:
    queue.name: smpp.outbound
    routing.key: smpp_direct_to_outbound

smpp:
  mo:
    host: 172.20.0.2
    port: 9550
    systemId: smpp_mo
    password: mo123
    systemType: cp
    bind-timeout: 5000
    enquire-link-timer: 40
    transaction-timer: 60000
    charset: UTF-8
  mt:
    host: 172.20.0.2
    port: 9550
    systemId: smpp_mt
    password: mt123
    systemType: cp
    bind-timeout: 5000
    enquire-link-timer: 40
    transaction-timer: 60000
    charset: UTF-8

logging:
  level:
    org.springframework: info
    org.jsmpp: info
    org.jsmpp.session.SMPPSession: info
    org.jsmpp.session.SMPPServerSession: info
    org.jsmpp.sample.springboot: info